name: auto_orientation_v2
description: Set the device orientation programmatically for iOS and Android
version: 2.3.2
homepage: https://github.com/rizkyghofur/auto_orientation
repository: https://github.com/rizkyghofur/auto_orientation
issue_tracker: https://github.com/rizkyghofur/auto_orientation/issues

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: de.bytepark.autoorientation
        pluginClass: AutoOrientationPlugin
      ios:
        pluginClass: AutoOrientationPlugin
