name: auto_orientation_v2
description: Set and control device orientation programmatically for Flutter apps on iOS and Android.
version: 2.4.1
homepage: https://github.com/rizkyghofur/auto_orientation_v2
repository: https://github.com/rizkyghofur/auto_orientation_v2
issue_tracker: https://github.com/rizkyghofur/auto_orientation_v2/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.rizkyghofur.autoorientation
        pluginClass: AutoOrientationPlugin
      ios:
        pluginClass: AutoOrientationPlugin
      web:
        pluginClass: AutoOrientationPlugin
        fileName: auto_orientation_v2.dart
      windows:
        pluginClass: AutoOrientationPlugin
        fileName: auto_orientation_v2.dart
      macos:
        pluginClass: AutoOrientationPlugin
        fileName: auto_orientation_v2.dart
      linux:
        pluginClass: AutoOrientationPlugin
        fileName: auto_orientation_v2.dart
